import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

const sizes = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  iconXs: 12,
  iconSm: 16,
  iconMd: 24,
  iconLg: 32,
  fontSizeSm: 14,
  fontSizeMd: 16,
  fontSizeLg: 50,
  buttonHeight: 18,
  buttonRedius: 12,
  buttonWidth: 120,
  appBarHeight: 56,
  imagesThubSize: 80,
  defaultSpace: 24,
  spaceBtwItems: 16,
  spaceBtwSections: 32,
  borderRadiusSm: 4,
  borderRadiusMd: 8,
  borderRadiusLg: 12,
  dividerHeight: 1,
  productImageSize: 120,
  productImageRadius: 16,
  productItemHeight: 160,
  inputFieldRadius: 12,
  spaceBtnInputFields: 16,
  cardRadiusXs: 6,
  cardRadiusSm: 10,
  cardRadiusMd: 12,
  cardRadiusLg: 16,
  cardElevation: 2,
  imagesCarousalHeight: 200,
  loadingIndicatorSize: 36,
  gridViewSpacing: 16,
};

export default sizes;
